#!/usr/bin/env bash

checkupdates=$(checkupdates)
if [[ "" == "$checkupdates" ]]; then
    updates=0
else
    updates=$(echo "$checkupdates" | wc -l)
fi

# long
echo "$updates updates"

# short
echo "$updates updates"

if echo "$checkupdates" | grep "^linux\|^systemd" > /dev/null 2>&1; then
    echo "#FF0000";
    exit 33;
elif [[ $updates -gt 100 ]]; then
    echo "#FF0000";
elif [[ $updates -gt 50 ]]; then
    echo "#FFFC00";
fi

