#!/usr/bin/env bash

# refresh (fwupdmgr will limit by itself)
fwupdmgr refresh > /dev/null 2>&1

fwupdates=$(
    fwupdmgr get-updates 2>&1 \
        | grep -ci 'No updates available for remaining devices'
)
if [[ $fwupdates -eq 1 ]]; then
    output="No firmware updates"
else
    output="Firmware updates"
fi

# long
echo "$output"

# short
echo "$output"

if [[ $fwupdates -eq 0 ]]; then
    echo "#999999";
else
    echo "#FFFC00";
fi
