#!/bin/bash
setxkbmap be &
if which xautolock > /dev/null 2>&1; then
    xautolock -time 5 -locker 'i3lockscreen' &
fi
if which dunst > /dev/null 2>&1; then
    dunst &
fi
if which compton > /dev/null 2>&1; then
    compton -C -I0 -O0 &
elif which xcompmgr > /dev/null 2>&1; then
    xcompmgr -C &
fi
if which start-pulseaudio-x11 > /dev/null 2>&1; then
    start-pulseaudio-x11 &
fi
if which nm-applet > /dev/null 2>&1; then
    nm-applet &
fi
if which udiskie > /dev/null 2>&1; then
    udiskie -t -F -A &
fi
if which cbatticon > /dev/null 2>&1; then
    cbatticon -u 120 -l 15 -n &
fi
if which parcellite > /dev/null 2>&1; then
    parcellite &
fi
if which keepassx2 > /dev/null 2>&1; then
    keepassx2 &
fi
