#!/bin/bash
setxkbmap be &
if [[ -x /usr/lib/polkit-kde-authentication-agent-1 ]]; then
    # pacman -S polkit-kde-agent
    /usr/lib/polkit-kde-authentication-agent-1 &
elif [[ -x /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 ]]; then
    # pacman -S mate-polkit
    /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
elif [[ -x /usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit ]]; then
    # pacman -S pantheon-polkit-agent
    /usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit &
elif [[ -x /usr/bin/lxqt-policykit-agent ]]; then
    # pacman -S lxqt-policykit
    /usr/bin/lxqt-policykit-agent &
elif [[ -x /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ]]; then
    # pacman -S polkit-gnome
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi
if which picom > /dev/null 2>&1; then
    picom &
elif which compton > /dev/null 2>&1; then
    compton &
fi
if which xss-lock > /dev/null 2>&1; then
    xss-lock -l -- i3lockscreen &
elif which xautolock > /dev/null 2>&1; then
    xautolock -time 5 -locker 'i3lockscreen' &
fi
if which dunst > /dev/null 2>&1; then
    dunst &
fi
if which start-pulseaudio-x11 > /dev/null 2>&1; then
    start-pulseaudio-x11 &
fi
if which nm-applet > /dev/null 2>&1; then
    nm-applet &
fi
if which blueman-applet > /dev/null 2>&1; then
    blueman-applet &
fi
if which udiskie > /dev/null 2>&1; then
    udiskie -t -F -A &
fi
if which cbatticon > /dev/null 2>&1; then
    cbatticon -u 120 -l 15 &
fi
if which copyq > /dev/null 2>&1; then
    copyq &
elif which parcellite > /dev/null 2>&1; then
    parcellite &
fi
if which firewall-applet > /dev/null 2>&1; then
    firewall-applet &
fi
if which redshift-gtk > /dev/null 2>&1; then
    redshift-gtk &
fi
if which keepassxc > /dev/null 2>&1; then
    keepassxc &
fi
if which ssh-add > /dev/null 2>&1; then
    ssh-add &
fi
if which autostart.sh > /dev/null 2>&1; then
    autostart.sh &
fi
