#!/bin/sh
function i3_exit {
    i3autostop suspend
    if [[ "$XDG_SESSION_DESKTOP" = "i3" ]]; then
    i3-msg exit
    elif [[ "$XDG_SESSION_DESKTOP" = "openbox" ]]; then
        openbox --exit
    fi
}

function i3_suspend {
    i3autostop suspend
    if ! ps aux | grep -q '[x]ss-lock'; then
        i3_lock
    fi
    if which systemctl > /dev/null 2>&1; then
        systemctl suspend
    else
        sudo /usr/sbin/pm-suspend
    fi
}

function i3_hibernate {
    i3autostop suspend
    if ! ps aux | grep -q '[x]ss-lock'; then
        i3_lock
    fi
    if which systemctl > /dev/null 2>&1; then
        systemctl hibernate
    else
        sudo /usr/sbin/pm-hibernate
    fi
}

function i3_reboot {
    i3autostop reboot
    if which systemctl > /dev/null 2>&1; then
        systemctl reboot
    else
        sudo /sbin/reboot
    fi
}

function i3_poweroff {
    i3autostop reboot
    if which systemctl > /dev/null 2>&1; then
        systemctl poweroff
    else
        sudo /sbin/poweroff
    fi
}

function i3_lock {
    if ps aux | grep -q '[x]ss-lock'; then
        xset s activate
    elif ps aux | grep -q '[x]autolock'; then
        xautolock -locknow
    else
        i3lockscreen &
        sleep 1
    fi
}

case "$1" in
    lock)
        i3_lock
        ;;
    logout)
        i3_exit
        ;;
    suspend)
        i3_suspend
        ;;
    hibernate)
        i3_hibernate
        ;;
    reboot)
        i3_reboot
        ;;
    shutdown)
        i3_poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
