#!/bin/sh
function i3_exit {
    i3autostop suspend
    i3-msg exit
}

function i3_suspend {
    i3autostop suspend
    if which systemctl > /dev/null 2>&1; then
        systemctl suspend
    else
        sudo /usr/sbin/pm-suspend
    fi
}

function i3_hibernate {
    i3autostop suspend
    if which systemctl > /dev/null 2>&1; then
        systemctl hibernate
    else
        sudo /usr/sbin/pm-hibernate
    fi
}

function i3_reboot {
    i3autostop reboot
    if which systemctl > /dev/null 2>&1; then
        systemctl reboot
    else
        sudo /sbin/reboot
    fi
}

function i3_poweroff {
    i3autostop reboot
    if which systemctl > /dev/null 2>&1; then
        systemctl poweroff
    else
        sudo /sbin/poweroff
    fi
}

function i3_lock {
    if which xautolock > /dev/null 2>&1; then
        xautolock -locknow
    else
        i3lockscreen
    fi
}

case "$1" in
    lock)
        i3_lock
        ;;
    logout)
        i3_exit
        ;;
    suspend)
        xautolock -locknow && i3_suspend
        ;;
    hibernate)
        xautolock -locknow && i3_hibernate
        ;;
    reboot)
        i3_reboot
        ;;
    shutdown)
        i3_poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
