#!/bin/sh
dpms_off() {
    xset dpms 0 0 0
}

dpms_on() {
    xset dpms 5 5 5
}

lockscreen() {
    if which xsecurelock > /dev/null 2>&1; then
        trap dpms_off SIGHUP SIGINT SIGTERM
        dpms_on
        xsecurelock
        dpms_off
    elif which i3lock > /dev/null 2>&1; then
        trap dpms_off SIGHUP SIGINT SIGTERM
        dpms_on
        i3lock -n -I 5 -c 000000
        dpms_off
    elif which slock > /dev/null 2>&1; then
        slock
    fi
}

lockscreen
