#!/bin/bash

boot=$(grep -e '\/boot\s' /etc/mtab)
boot_found=$?

if [[ $boot_found -ne 0 ]]; then
	sudo mount /boot
fi

boot=$(grep -e '\/boot\s' /etc/mtab)
boot_rw=$(echo "$boot" | grep 'rw')
boot_rw_found=$?

if [[ $boot_rw_found -ne 0 ]]; then
	echo "Please make sure /boot is mounted rw"
	exit $boot_rw_found
fi

/usr/bin/pacman $@

boot=$(grep -e '\/boot\s' /etc/mtab)
boot_found=$?

if [[ $boot_found -eq 0 ]]; then
	sudo umount /boot
fi
