#!/bin/bash
sleep 4
if [[ -x /usr/lib/polkit-kde-authentication-agent-1 ]]; then
    # pacman -S polkit-kde-agent
    /usr/lib/polkit-kde-authentication-agent-1 &
elif [[ -x /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 ]]; then
    # pacman -S mate-polkit
    /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
elif [[ -x /usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit ]]; then
    # pacman -S pantheon-polkit-agent
    /usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit &
elif [[ -x /usr/bin/lxqt-policykit-agent ]]; then
    # pacman -S lxqt-policykit
    /usr/bin/lxqt-policykit-agent &
elif [[ -x /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ]]; then
    # pacman -S polkit-gnome
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi
if which swayidle > /dev/null 2>&1; then
    swayidle -w \
        timeout 300 'swaylock -f -c 000000' \
        timeout 600 'swaymsg "output * dpms off"' \
            resume 'swaymsg "output * dpms on"' \
        before-sleep 'swaylock -f -c 000000' &
fi
if which wl-paste && which clipman; then
    wl-paste -p -t text --watch \
        clipman store -P \
        --max-items=0 \
        --histpath="~/.local/share/clipman-primary.json" &
fi
if which mako > /dev/null 2>&1; then
    mako &
fi
if which start-pulseaudio-x11 > /dev/null 2>&1; then
    start-pulseaudio-x11 &
fi
if which nm-applet > /dev/null 2>&1; then
    nm-applet --indicator &
fi
if which blueman-applet > /dev/null 2>&1; then
    blueman-applet &
fi
#if which udiskie > /dev/null 2>&1; then
    #udiskie -t -F -A &
#fi
#if which firewall-applet > /dev/null 2>&1; then
    #firewall-applet &
#fi
if which keepassxc > /dev/null 2>&1; then
    keepassxc &
fi
if which ssh-add > /dev/null 2>&1; then
    ssh-add &
fi
if which autostart.sh > /dev/null 2>&1; then
    autostart.sh &
fi
