#!/usr/bin/env bash

session_name="$(basename "$(pwd)")"
if [[ -n "$1" ]]; then
    session_name="$1"
fi

if tmux has-session -t "$session_name"; then
    exec tmux a -t "$session_name"
else
    exec tmux new -s "$session_name"
fi
