#!/usr/bin/env bash

sed -e '1s/^/@import url("custom.css");/' -i /opt/vivaldi-snapshot/resources/vivaldi/style/common.css

cat > /opt/vivaldi-snapshot/resources/vivaldi/style/custom.css <<EOF
#browser.native.linux:not(.tabs-top) div#header {
  display: none;
}
EOF
